version: 2
jobs:
  build:
    docker:
      - image: node:12.2.0-alpine

    # working_directory: ~/
    # branches:
    #   only:
    #     - develop
    steps:
      - checkout
      - run: npm install

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: develop
